[package]
name = "mmmpm_storage_filesystem"
version = "0.1.0"
authors = ["t-sin <shinichi.tanaka45@gmail.com>"]
description = "A storage abstraction: Filesystem"
edition = "2018"

[dependencies]
mmmpm_storage = { path = "../storage" }
